#!/bin/bash

if [ -z $1 ];
then
	echo "ERROR: Please provide distribution like so:"
	echo -e "\t$0 focal"
fi

container_name="$(petname)-$1"

lxc launch images:ubuntu/$1 ${container_name}
sleep 3
lxc exec ${container_name} -- apt-get update -y && apt upgrade -y
lxc exec ${container_name} -- apt install -y software-properties-common
lxc exec ${container_name} -- bash
